### ISSUE TITLE
Unable to start the examples

### ISSUE THREAD

**Issue by sefibk** [Deeplite/deeplite-torch-zoo#21]
I signed-up and got the license but couldn't find documentation as to how to register it.
Is there such documentation?
When I try to run the examples I get the following message - could you assist?

`2021-05-31 19:54:04 - ERROR: The license is invalid!
Traceback (most recent call last):
  File "neutrino/nlicensing.py", line 43, in neutrino.nlicensing.Singleton.instance
AttributeError: 'Singleton' object has no attribute '_instance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/hello_neutrino_classifier.py", line 3, in <module>
    from neutrino.framework.torch_framework import TorchFramework
  File "neutrino/framework/torch_framework.py", line 9, in init neutrino.framework.torch_framework
  File "neutrino/framework/torch_distributed.py", line 7, in init neutrino.framework.torch_distributed
  File "neutrino/framework/distributed.py", line 52, in init neutrino.framework.distributed
  File "neutrino/nlicensing.py", line 172, in neutrino.nlicensing.FeaturesLicense.__init__
  File "neutrino/nlicensing.py", line 45, in neutrino.nlicensing.Singleton.instance
  File "neutrino/nlicensing.py", line 86, in neutrino.nlicensing.License.__init__
AssertionError: None`

**Comment by yasseridris** [comment]
Hello @sefibk, You can find the information on how to use the license [here](https://docs.deeplite.ai/neutrino/license.html#use-license). Please let me know if that helps.

**Comment by goodboyanush** [comment]
Closing due to inactivtiy.

**Comment by goodboyanush-deeplite** [comment]
Closing due to inactivity.
