### ISSUE TITLE
Setuptools causing build error

### ISSUE THREAD

**Issue by alexh-deeplite** [Deeplite/deeplite-torch-zoo#395]
There is a known change in the new version of setuptools that is causing build issues for users.
 
We are experiencing this issue when calling `pip install .`. There appear to be a few solutions so I will investigate the best one for us

https://github.com/pypa/setuptools/issues/4483

**Comment by alexh-deeplite** [comment]
Error dump:
```6.70s$ pip install .
Processing /home/travis/build/Deeplite/deeplite-torch-zoo
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-fwxetynh/deeplite_torch_zoo.egg-info
      writing /tmp/pip-pip-egg-info-fwxetynh/deeplite_torch_zoo.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-fwxetynh/deeplite_torch_zoo.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-pip-egg-info-fwxetynh/deeplite_torch_zoo.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-fwxetynh/deeplite_torch_zoo.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-fwxetynh/deeplite_torch_zoo.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-pip-egg-info-fwxetynh/deeplite_torch_zoo.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.md'
      adding license file 'NOTICE.txt'
      /home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages/setuptools/__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/travis/build/Deeplite/deeplite-torch-zoo/setup.py", line 45, in <module>
          setup(
        File "/home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages/setuptools/dist.py", line 956, in run_command
          super().run_command(command)
        File "/home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 310, in run
          self.find_sources()
        File "/home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 318, in find_sources
          mm.run()
        File "/home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 544, in run
          self.prune_file_list()
        File "/home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 610, in prune_file_list
          base_dir = self.distribution.get_fullname()
        File "/home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages/setuptools/_core_metadata.py", line 266, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "/home/travis/virtualenv/python3.8.13/lib/python3.8/site-packages/setuptools/_core_metadata.py", line 284, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
The command "pip install ." failed and exited with 1 during .
```
